version: '2'

services:
  mysql:
    image: mysql
    container_name: mysql-autoBeheerService
    environment:
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: autobeheerserviceDB
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: 12341234
    ports:
      - 6012:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-autoBeheerService
    links:
     - mysql:db
    ports:
     - 6011:80

  lapiwe.autobeheerservice.facade:
    image: lapiwe/lapiwe.autobeheerservice.facade${TAG}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      'ConnectionStrings:DataAccessMySqlProvider': server=db;userid=admin;password=admin;database=autobeheerserviceDB;
    links:
     - mysql:db
    ports:
     - 6013:80
    networks:
      - eventbus-network

networks:
  eventbus-network:
    external:
      name: eventbus-network